# This is a basic workflow that is manually triggered

name: LiteChat Workflows

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: main

jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       - name: 签出代码
         uses: actions/checkout@main
       - name: 发布阿里云
         uses: wlixcc/SFTP-Deploy-Action@v1.0 # 使用 SFTP 协议上传
         with:
           username: 'wyz'
           server: '${{ secrets.Ali_SERVER_HOST }}'
           ssh_private_key: '${{ secrets.Ali_SERVER_PRIVATE_KEY }}'
           local_path: 'dist/*'
           remote_path: '/home/wyz/LiteChat-Client/dist/'
           args: "-o ConnectTimeout=5"
